class AddIndexes < ActiveRecord::Migration[5.2]
  def change
  	#add_index :people, :uuid, name: 'uuid'
  	#add_index :person_names, :uuid, name: 'uuid'
  	# add_index :person_addresses, :uuid, name: 'uuid'
  	# add_index :relationships, :uuid, name: 'uuid'
  	# add_index :users, :uuid, name: 'uuid'
  	# add_index :identifiers, :uuid, name: 'uuid'
  	# add_index :outcomes, :uuid, name: 'uuid'
  	# add_index :breastfeeding_statuses, :uuid, name: 'uuid'
  	# add_index :diagnosis, :uuid, name: 'uuid'
  	# add_index :appointments, :uuid, name: 'uuid'
  	# add_index :pregnant_statuses, :uuid, name: 'uuid'
  	# add_index :patient_histories, :uuid, name: 'uuid'
  	# add_index :family_plannings, :uuid, name: 'uuid'
  	# add_index :presenting_complaints, :uuid, name: 'uuid'
  	# add_index :lab_orders, :uuid, name: 'uuid'
  	# add_index :vitals, :uuid, name: 'uuid'
  	# add_index :symptoms, :uuid, name: 'uuid'
  	# add_index :tb_statuses, :uuid, name: 'uuid'
  	# add_index :hts_results_givens, :uuid, name: 'uuid'
  	# add_index :medication_prescriptions, :uuid, name: 'uuid'
  	# add_index :medication_dispensations, :uuid, name: 'uuid'
  	# add_index :medication_adherences, :uuid, name: 'uuid'
  	# add_index :side_effects, :uuid, name: 'uuid'
  	# add_index :occupations, :uuid, name: 'uuid'
  end
end
