class RemoveUuidIndexes < ActiveRecord::Migration[5.2]
  def change
    remove_index :people, name: 'uuid'
    remove_index :person_names, name: 'uuid'
    remove_index :person_addresses, name: 'uuid'
    remove_index :relationships, name: 'uuid'
    remove_index :users, name: 'uuid'
    remove_index :identifiers, name: 'uuid'
    remove_index :outcomes, name: 'uuid'
    remove_index :breastfeeding_statuses, name: 'uuid'
    remove_index :diagnosis, name: 'uuid'
    remove_index :appointments, name: 'uuid'
    remove_index :pregnant_statuses, name: 'uuid'
    remove_index :patient_histories, name: 'uuid'
    remove_index :family_plannings, name: 'uuid'
    remove_index :presenting_complaints, name: 'uuid'
    remove_index :lab_orders, name: 'uuid'
    remove_index :vitals, name: 'uuid'
    remove_index :symptoms, name: 'uuid'
    remove_index :tb_statuses, name: 'uuid'
    remove_index :hts_results_givens, name: 'uuid'
    remove_index :medication_prescriptions, name: 'uuid'
    remove_index :medication_dispensations, name: 'uuid'
    remove_index :medication_adherences, name: 'uuid'
    remove_index :side_effects, name: 'uuid'
    remove_index :occupations, name: 'uuid'
  end
end
